grant select on BORDER_CROSSING_CHILDREN_SEQ to MIGRATION;
grant select on BORDER_CROSSING_ESCALATE_SEQ to MIGRATION;
grant select on BORDER_CROSSING_SEQ to MIGRATION;
grant select on IMAGE_SEQ to MIGRATION;
grant select on VERIFICATION_RESULT_SEQ to MIGRATION;
